---
ReportDefinitions:
- reportName: UlbWiseWaterChargeCollection
  summary: State Wide Water Charge Collection
  version: 1.0.0
  moduleName: rainmaker-ws
  sourceColumns:
  - name: ulb
    label: reports.pt.ulb
    type: string
    source: pt
    total: false
  - name: connectionno
    label: Connection No
    type: string
    source: pt
    total: false
  - name: oldconnectionno
    label: Old Connection No
    type: string
    source: pt
    total: false
  - name: connectiontype
    label: Connection Type
    type: string
    source: pt
    total: false
  - name: meterid
    label: Meter Id
    type: string
    source: pt
    total: false
  - name: totaltaxamt
    label: Total Demand Amount
    type: string
    source: pt
    total: true
  - name: totalcollectedamt
    label: Collected Amount
    type: string
    source: pt
    total: true
  - name: dueAmount
    label: Due Amount
    type: string
    source: pt
    total: true
  searchParams:
  - name: tenant
    label: Tenant
    type: singlevaluelist
    pattern: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?moduleName=tenant&masterName=tenants&tenantId=od|$..code|$..name
    source: pt
    wrapper: true
    isMandatory: false
    searchClause: AND ewc.tenantid = $tenant
  query: |
      SELECT INITCAP(SPLIT_PART(EWC.TENANTID,'.',2)) AS ULB,EWC.CONNECTIONNO,EWC.OLDCONNECTIONNO,EWS.CONNECTIONTYPE,EWS.METERID,COALESCE(DM.TOTALTAXAMT,0) AS TOTALTAXAMT,COALESCE(DM.TOTALCOLLECTEDAMT,0) AS TOTALCOLLECTEDAMT,COALESCE(DM.TOTALTAXAMT,0) - COALESCE(DM.TOTALCOLLECTEDAMT,0) AS DUEAMOUNT FROM EG_WS_CONNECTION EWC INNER JOIN EG_WS_SERVICE EWS ON EWC.ID = EWS.CONNECTION_ID LEFT OUTER JOIN (SELECT EDV.CONSUMERCODE,SUM(EDV2.TAXAMOUNT) AS TOTALTAXAMT,SUM(EDV2.COLLECTIONAMOUNT) AS TOTALCOLLECTEDAMT FROM EGBS_DEMAND_V1 EDV INNER JOIN EGBS_DEMANDDETAIL_V1 EDV2 ON EDV.ID = EDV2.DEMANDID GROUP BY EDV.CONSUMERCODE) DM ON EWC.APPLICATIONNO = DM.CONSUMERCODE WHERE EWC.APPLICATIONSTATUS = 'CONNECTION_ACTIVATED' AND EWC.ISOLDAPPLICATION = FALSE
  orderby: ORDER BY ewc.tenantid DESC NULLS LAST